version: "3"

services:
  beamdaq:
    image: beamdaq:latest
    build: beam/
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    network_mode: host

  scalerdaq:
    image: scalerdaq:latest
    build: scaler/
    # entrypoint: /bin/tcsh
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - /localstorage/daq/scaler/coda:/usr/local/coda
      - /localstorage/data/scaler:/opt/coda/data
    network_mode: bridge
    # networks:
      # local-only:
        # ipv4_address: 192.168.24.15    
    ports:
      - "69:69"
      - "8101:8101"
      - "11111:11111"
      - "45001:45001"
      - "45301:45301"
      - "45303:45303"
      - "45305:45305"
      - "38359:38359"
      - "45400:45400"
      - "32898:32898"
      - "45401:45401"
      - "33828:33828"

networks:
  local-only:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.26.0/24
          gateway: 192.168.26.71


