services:
  beamdaq:
    image: beamdaq:latest
    build: beam/
    restart: always
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
     - DISPLAY=${DISPLAY}
     - TZ=America/Chicago
     - BEAMDAQ_DIR=/data4/dockerDAQ/daq/seaquest-daq/BeamDAQ/
    volumes:
     - /tmp/.X11-unix:/tmp/.X11-unix
     - ~/.Xauthority:/root/.Xauthority
     - /data2:/data2
     - /data4:/data4
    network_mode: host

  scalerdaq:
    image: scalerdaq:latest
    build: scaler/
    hostname: e1039sc4.sq.pri
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - DISPLAY=${DISPLAY}
      - FTP_USER=e1039daq
      - FTP_PASS=ftp
      - TZ=America/Chicago
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/.Xauthority:/root/.Xauthority
      - ~/.Xauthority:/home/e1039daq/.Xauthority
      - /data4/dockerDAQ/daq/scaler/coda:/usr/local/coda
      - /data4/dockerDAQ/data/scaler:/opt/coda/data
      - /data2:/data2
      - /data4:/data4
      - /data4/dockerDAQ/data/scaler:/home/e1039daq/data
    networks:
      scaler_vlan:
        ipv4_address: 192.168.24.14   

networks:
  scaler_vlan:
    driver: macvlan
    driver_opts:
      parent: eno1
    ipam:
      config:
        - subnet: "192.168.24.0/24"
          gateway: "192.168.24.71"
